Fixes policy CMP0135 warning for CMake >= 3.24
ros2/console_bridge_vendor pull request #36
Opened 2022-09-09 20:36 UTC by Crola1702

Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>

Reference build: https://ci.ros2.org/view/nightly/job/nightly_win_deb/2473/

[This](https://cmake.org/cmake/help/latest/policy/CMP0135.html) warning started appearing on new windows machines. It’s caused by a new CMake version (3.24) that expects this policy to be set.

This PR sets CMP0135 policy in CMakeLists.txt

CI launch:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17257)](http://ci.ros2.org/job/ci_linux/17257/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11796)](http://ci.ros2.org/job/ci_linux-aarch64/11796/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17737)](http://ci.ros2.org/job/ci_windows/17737/)

2022-09-09 20:39 UTC, clalancette requested changes

2022-09-09 20:39 UTC, clalancette commented on CMakeLists.txt
> +if (POLICY CMP0135)
```suggestion
if(POLICY CMP0135)
```

(this is why the Rpr job is failing)

2022-09-12 14:33 UTC, clalancette approved these changes
Looks good with green CI.

2022-09-12 14:39 UTC, Crola1702 commented
New builds with CI_launcher:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17275)](http://ci.ros2.org/job/ci_linux/17275/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11815)](http://ci.ros2.org/job/ci_linux-aarch64/11815/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17756)](http://ci.ros2.org/job/ci_windows/17756/)

2022-09-12 14:39 UTC, merged

2022-12-29 18:50 UTC, emersonknapp commented
@mergifyio backport humble

2022-12-29 18:55 UTC, emersonknapp commented
@Crola1702 @clalancette can we backport this to Humble? I'm pretty sure it's the issue I'm seeing in https://ci.ros2.org/job/ci_windows/18536/

I don't have the right/write permissions here to do it myself

2023-01-02 18:51 UTC, clalancette commented
@Mergifyio backport humble